import { describe, it, expect } from 'vitest';
import { Mulberry32 } from '../src/pool/mulberry32';

// Mulberry32 known-vector + edge-case coverage. The vectors below were
// generated by running the TS implementation in `pnpm exec tsx` and then
// cross-validated against scripts/generate_pool.py (the Python twin):
//   $ python3 -c "from generate_pool import Mulberry32; r=Mulberry32(42);
//       print([r.next_u32() for _ in range(5)])"
// Both runtimes produce identical bit-exact output, which is the
// algorithm's whole point — keep it that way.

describe('Mulberry32 — known-vector (cross-validated against scripts/generate_pool.py)', () => {
  it('seed=42 → first 5 nextU32() values match the frozen vector', () => {
    const r = new Mulberry32(42);
    const got = [r.nextU32(), r.nextU32(), r.nextU32(), r.nextU32(), r.nextU32()];
    expect(got).toEqual([2581720956, 1925393290, 3661312704, 2876485805, 750819978]);
  });

  it('seed=42 → first 5 nextFloat() values match the frozen vector', () => {
    const r = new Mulberry32(42);
    const got = [r.nextFloat(), r.nextFloat(), r.nextFloat(), r.nextFloat(), r.nextFloat()];
    expect(got).toEqual([
      0.6011037519201636, 0.44829055899754167, 0.8524657934904099, 0.6697340414393693,
      0.17481389874592423,
    ]);
  });

  it('seed=0 → first 5 nextFloat() values match the frozen vector (no NaN, no zero-stuck)', () => {
    const r = new Mulberry32(0);
    const got = [r.nextFloat(), r.nextFloat(), r.nextFloat(), r.nextFloat(), r.nextFloat()];
    expect(got).toEqual([
      0.26642920868471265, 0.0003297457005828619, 0.2232720274478197, 0.1462021479383111,
      0.46732782293111086,
    ]);
    for (const v of got) {
      expect(Number.isFinite(v)).toBe(true);
      expect(Number.isNaN(v)).toBe(false);
    }
  });
});

describe('Mulberry32 — algorithm invariants', () => {
  it('two instances with the same seed produce the same sequence (10 floats)', () => {
    const a = new Mulberry32(12345);
    const b = new Mulberry32(12345);
    for (let i = 0; i < 10; i++) {
      expect(a.nextFloat()).toBe(b.nextFloat());
    }
  });

  it('different seeds produce different first values', () => {
    const a = new Mulberry32(1).nextU32();
    const b = new Mulberry32(2).nextU32();
    expect(a).not.toBe(b);
  });

  it('every nextFloat() value satisfies 0 ≤ x < 1', () => {
    const r = new Mulberry32(7);
    for (let i = 0; i < 10_000; i++) {
      const v = r.nextFloat();
      expect(v).toBeGreaterThanOrEqual(0);
      expect(v).toBeLessThan(1);
    }
  });

  it('period sanity — 10 000 draws, no early repeat of the first value', () => {
    const r = new Mulberry32(99);
    const first = r.nextU32();
    for (let i = 0; i < 10_000; i++) {
      expect(r.nextU32()).not.toBe(first);
    }
  });

  it('uint32 normalization — seed=2**32 behaves identically to seed=0', () => {
    // The constructor applies `seed >>> 0`. 2**32 (4294967296) wraps to 0
    // through the unsigned right-shift. Cross-validated against the same
    // behavior in the Python twin's `seed & UINT32_MASK`.
    const a = new Mulberry32(2 ** 32);
    const b = new Mulberry32(0);
    expect(a.nextU32()).toBe(b.nextU32());
    expect(a.nextU32()).toBe(b.nextU32());
    expect(a.nextU32()).toBe(b.nextU32());
  });

  it('negative seeds normalize to uint32 deterministically', () => {
    // -1 >>> 0 === 0xFFFFFFFF; assert that the first u32 is reproducible.
    const a = new Mulberry32(-1).nextU32();
    const b = new Mulberry32(0xffffffff).nextU32();
    expect(a).toBe(b);
  });
});
